### ISSUE TITLE
messenger.com new version breaks the themes

### ISSUE THREAD

**Issue by ShinySnicket** [liorgrossman/darkness#238]
**Bug Information**
(visit the affected website → click the moon icon → "Send Feedback" → "Bug Report" → paste here)
* Site: messenger
* Theme: dusk
* URL: https://www.messenger.com/t/100000464907991
* Darkness Version: 2.0.25 Pro
* Browser: Chrome 87.0.4280.88
* Operating System: Windows 10
* Resolution: 1920x1200
* Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/87.0.4280.88 Safari/537.36

**Bug Description**
Messenger.com got an update, and now Darkness looks bad, no matter what theme I choose. My messages' background color is harsh on the eyes, and the anti-aliasing on the text looks bad.

**Screenshots**
If necessary, add screenshots to help explain your problem.
![image](https://user-images.githubusercontent.com/66476297/102514593-5547b680-4095-11eb-82c4-65df5c56148e.png)

**Comment by theme1256** [comment]
This is fixed.

**Comment by ShinySnicket** [comment]
Hi, the problem persists on my end. Is there a new version of Darkness that I need to update to? My version is still 2.0.25
I restarted Chrome to make sure.

**Comment by liorgrossman** [comment]
I uploaded 2.0.26 to Chrome Web Store, but it's still pending review, hopefully they approve it soon

**Comment by ShinySnicket** [comment]
Thanks :)
