### ISSUE TITLE
Fullscreen YouTube videos have inverted colors in facebook

### ISSUE THREAD

**Issue by halflings** [liorgrossman/darkness#4]
When I'm using Darkness in facebook and try to put a video fullscreen, it's shown with inverted colors. Tested on Mac OS and Linux (Ubuntu).

**Comment by liorgrossman** [comment]
Thanks for reporting. This is fixed on the latest version, please pull and do gulp sass:compile

**Comment by Arigatex** [comment]
This is still a problem in the Firefox version
![image](https://user-images.githubusercontent.com/32854335/51741515-7a913d00-2097-11e9-9a18-69d6fad9ccbd.png)
